### ISSUE TITLE
Error message while Running `python manage.py migrate`

### ISSUE THREAD

**Issue by darkcheftar** [Ram-95/blog_application_django#9]
>% (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting TEMPLATES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by Ram-95** [comment]
@darkcheftar 
I have updated the ```README.md``` with all the steps needed to set up the application. Please go through it.

If you still face any issues feel free to comment your issue here. Thanks!

**Comment by Ram-95** [comment]
@darkcheftar Are you able to run the application ?

**Comment by darkcheftar** [comment]
@Ram-95 Yes, Thank you. ❤️
